### ISSUE TITLE
Upgrade to Vuejs >=2.0

### ISSUE THREAD

**Issue by throrin19** [bastienGranger/vue-datepicker#4]
Hi,
It's possible to upgrade your component to VueJS 2.0+ ?

Thanks

**Comment by bastienGranger** [comment]
Hi,

Yes I can ! I will try to do it this week.
Did you try the component ?
Do you have any feedbacks ?

Bastien

**Comment by mycarrysun** [comment]
Hey @bastienGranger, looking to use it my Vue 2.0 project as well. Will this take a long time? I have a deadline of the 23rd. No worries if it will take longer, I will find something else to use in the meantime but I love the UI of the current design and there's not many other options that are Vue 2.0 ready.

**Comment by bastienGranger** [comment]
I’m working on it.

It will be ready today or tomorrow !

Bastien

**Comment by bastienGranger** [comment]
Hey @throrin19  and @mycarrysun, I've juste updated the component to use VueJS 2.1.6

Thanks for this issue !

Bastien

**Comment by mycarrysun** [comment]
@bastienGranger thank you so much! Love this package
